const fs = require('fs')
module.exports = {
    //前台页面的请求处理
    //render函数完成了三个事件
    //1.读取文件内容
    //2.如果有数据，就进行动态渲染
    //3.将渲染结果返回
    getIndexPage(req,res){
       res.render('index.ejs')
    },
    getDetailPage(req,res){
        res.render('detail.ejs')
    },
    getListPage(req,res){
        res.render('list.ejs')
    },
    //后台页面的请求处理
    getAdminIndexPage(req,res){
        res.render('admin/index.ejs')
    },
    getCategoriesPage(req,res){
        res.render('admin/categories.ejs')
    },
    getCommentsPage(req,res){
        res.render('admin/comments.ejs')
    },
    getLoginPage(req,res){
        res.render('admin/login.ejs')
    },
    getNavMenusPage(req,res){
        res.render('admin/nav-menus.ejs')
    },
    getPasswordResetPage(req,res){
        res.render('admin/password-reset.ejs')
    },
    getPostAddPage(req,res){
        res.render('admin/post-add.ejs')
    },
    getPostsPage(req,res){
        res.render('admin/posts.ejs')
    },
    getProfilesPage(req,res){
        res.render('admin/profile.ejs')
    },
    getSettingsPage(req,res){
        res.render('admin/settings.ejs')
    },
    getSlidesPage(req,res){
        res.render('admin/slides.ejs')
    },
    getUsersPage(req,res){
        res.render('admin/users.ejs')
    }
}